from pathlib import Path
from xml.sax.saxutils import escape
import json,textwrap
ROOT=Path(__file__).resolve().parents[1]; A=ROOT/'assets'; A.mkdir(exist_ok=True)
def svg(name,title,items):
 s=f'<svg xmlns="http://www.w3.org/2000/svg" width="900" height="620" viewBox="0 0 900 620" role="img" aria-labelledby="{name}-title"><title id="{name}-title">{escape(title)}</title><rect width="900" height="620" fill="#faf8f2"/><text x="42" y="55" font-family="sans-serif" font-size="26" fill="#24483f">{escape(title)}</text>'+''.join(items)+'</svg>'
 (A/(name+'.svg')).write_text(s)
def box(x,y,w,h,title,desc=''):
 lines=textwrap.wrap(desc,width=max(20,int((w-36)/9.8)))
 texts=''.join(f'<text x="{x+18}" y="{y+65+i*23}" font-family="sans-serif" font-size="19" fill="#455b54">{escape(line)}</text>' for i,line in enumerate(lines))
 return f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="14" fill="white" stroke="#78958b"/><text x="{x+18}" y="{y+34}" font-family="sans-serif" font-size="22" fill="#24483f">{escape(title)}</text>'+texts
svg('sala-controle','Sala de Controle · metáfora de escolha',[box(40+(i%2)*420,90+(i//2)*98,398,87,t,d) for i,(t,d) in enumerate([('Corpo','O que percebo fisicamente?'),('Fato','O que aconteceu?'),('Narrativa','O que minha mente acrescentou?'),('Origem','Como aprendi este pensamento?'),('Emoção','O que sinto?'),('Impulso','O que quero fazer agora?'),('Valor','Que princípio quero sustentar?'),('Escolha','Que resposta depende de mim?'),('Futuro','Quais consequências são possíveis?'),('Fruto','O que aconteceu depois?')])])
svg('fato-historia','Separar para enxergar',[box(50,130,800,110,'Fato','O que uma observação ou registro sustenta?'),box(50,270,800,110,'Narrativa','Que interpretação acrescentei ao acontecimento?'),box(50,410,800,110,'Incógnita','O que ainda preciso perguntar, testar ou não sei?')])
svg('habito-contexto','O comportamento acontece em um contexto',[box(40,100,395,110,'Contexto e oportunidade','Tempo, recursos, ambiente e outras pessoas.'),box(465,100,395,110,'Capacidade e motivação','Habilidades, energia, prioridades e emoções.'),box(245,270,410,110,'Ação possível','Escolher uma resposta pequena e específica.'),box(245,445,410,110,'Consequência e revisão','Observar; repetir, adaptar ou interromper.'),'<path d="M245 210L350 270M660 210L550 270M450 380V445M245 500Q80 400 150 210" fill="none" stroke="#78958b" stroke-width="3"/>'])
svg('arvore-frutos','Sua árvore, seus Frutos',[ '<path d="M445 480V260M445 370L300 230M445 330L610 210" fill="none" stroke="#715742" stroke-width="22"/><ellipse cx="445" cy="205" rx="270" ry="125" fill="#e4ebe1"/>','<path d="M445 480L350 550M445 480L535 550M445 480V565" stroke="#715742" fill="none" stroke-width="9"/>']+[f'<path d="M{x} {y}c-26 5-30 47 0 52c30-5 26-47 0-52" fill="#d1a057"/><path d="M{x-6} {y+48}q-16 28 8 18" stroke="#715742" fill="none" stroke-width="8"/>' for x,y in [(290,180),(440,130),(590,180)]]+[box(40,395,270,110,'Frutos = evidências','Não medem o seu valor.'),box(590,395,270,110,'Raízes e ambiente','Também afetam resultados.')])
svg('acucar-honesto','Tradução visual · exemplo hipotético',[box(50,110,800,110,'Rótulo fictício: 10 g de açúcar / 100 ml','Porção consumida: 200 ml. Não representa uma marca real.'),box(50,270,800,110,'10 × (200 ÷ 100) = 20 g','Massa de açúcar: 20 g. Não é um copo cheio de açúcar.'),box(50,430,800,110,'Antes de comparar, leia o rótulo real','Açúcares totais e adicionados são informações distintas.')])
svg('processo','Imaginar, contrastar e agir',[box(50,110,800,110,'Veja o processo','Imagine onde, quando e como fará uma ação concreta.'),box(50,270,800,110,'Reconheça o obstáculo','Qual barreira provável merece um plano?'),box(50,430,800,110,'Se acontecer X, então farei Y','Teste a resposta; observe o resultado; revise.')])
svg('planta','Uma escolha precisa continuar sendo cuidada',['<path d="M350 350H550L520 540H380Z" fill="#d4b390" stroke="#715742" stroke-width="3"/><path d="M450 355V170" stroke="#497760" stroke-width="10"/><path d="M450 250Q320 220 340 130Q460 140 450 250M450 205Q570 180 565 100Q455 120 450 205" fill="#789e70"/>','<text x="80" y="580" font-family="sans-serif" font-size="20" fill="#24483f">Plantar → cuidar → observar → ajustar. Símbolo, não mecanismo clínico.</text>'])
lookup={1:'sala-controle',2:'habito-contexto',3:None,4:'sala-controle',5:'habito-contexto',6:'fato-historia',7:'fato-historia',8:'fato-historia',9:'processo',10:'arvore-frutos',11:'arvore-frutos',12:'processo',13:'arvore-frutos',14:'sala-controle',15:'arvore-frutos',16:'processo',17:'arvore-frutos',18:'processo',19:'habito-contexto',20:'arvore-frutos',21:'sala-controle',22:'acucar-honesto',23:'processo',24:'habito-contexto',25:'sala-controle',26:'habito-contexto',27:'arvore-frutos',28:'processo',29:'processo',30:'planta'}
# Candidate mapping: renderers only insert assets when a block explicitly references one.
manifest=[{'id':f'v-d{d:02}','day':d,'concept':v,'function':'Orientar a prática e tornar relações explícitas','type':'svg_diagram','pdf_format':'vector 140mm wide','app_format':'responsive svg','alt':{'sala-controle':'Dez painéis: corpo, fato, narrativa, origem, emoção, impulso, valor, escolha, futuro e fruto.','acucar-honesto':'Exemplo hipotético: 10 g por 100 ml, em 200 ml resultam 20 g de açúcar.','arvore-frutos':'Árvore com cajus, raízes e lembrete de que resultados não medem valor pessoal.'}.get(v,(v or '').replace('-',' ')),'generation_prompt':None,'production':'Diagrama exato em código; não requer geração raster','path':('assets/'+v+'.svg') if v else None,'status':'produced; placement candidate pending editorial match'} for d,v in lookup.items()]
(ROOT/'visual-assets.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2))
svg('mmi','MMI 2.0 · como quero viver neste corpo?',[box(40+(i%2)*420,100+(i//2)*150,398,125,t,d) for i,(t,d) in enumerate([('Conforto e mobilidade','Vestir, sentar, caminhar, alcançar.'),('Força e energia','O que quero conseguir fazer?'),('Sono e cuidado','Que rotina me ampara?'),('Relação comigo','Que linguagem quero abandonar?'),('Aparência: opcional','Desejo estético não mede dignidade.'),('Manutenção','Qual cuidado cabe na vida real?')])])
svg('tradutor-prato','Tradutor do Prato · perguntas, não julgamento',[box(40+(i%2)*420,100+(i//2)*150,398,125,t,d) for i,(t,d) in enumerate([('Proteína','Qual fonte está presente?'),('Carboidrato','Qual fonte está presente?'),('Vegetais e fibras','Onde aparecem nesta refeição?'),('Repetição','Há fontes repetidas? Foi escolha?'),('Contexto','Acesso, cultura, fome e preferências.'),('Objetivo e cuidado','Há orientação individual a considerar?')])])
svg('abas-mentais','Nem toda aba precisa ficar aberta',[box(50,110,800,110,'Capture sem resolver tudo','Escreva uma frase por pendência.'),box(50,270,390,145,'Tem uma ação possível?','Escolha o menor próximo passo.'),box(465,270,385,145,'Não depende de você?','Nomeie o limite do seu alcance.'),box(50,460,800,105,'Uma prioridade volta à mesa','O restante fica registrado, não comandando o momento.')])
lookup={1:'sala-controle',2:'abas-mentais',3:None,4:'abas-mentais',5:'habito-contexto',6:'fato-historia',7:'fato-historia',8:'fato-historia',9:None,10:'sala-controle',11:None,12:'processo',13:'mmi',14:None,15:None,16:'arvore-frutos',17:None,18:'arvore-frutos',19:'processo',20:'habito-contexto',21:'mmi',22:'acucar-honesto',23:None,24:None,25:None,26:'habito-contexto',27:'habito-contexto',28:'arvore-frutos',29:'processo',30:'planta'}
for row in manifest:
 v=lookup[row['day']];row.update(concept=v or 'Prática textual',type='svg_diagram' if v else 'none',path='assets/'+v+'.svg' if v else None,status='produced' if v else 'no image: textual exercise sufficient',alt={'sala-controle':'Dez painéis de observação e escolha.','acucar-honesto':'Rótulo hipotético: 10 g por 100 ml; 200 ml contêm 20 g.','mmi':'Conforto, mobilidade, força, energia, sono, autocuidado e aparência opcional.','fato-historia':'Separar observação, interpretação e o que ainda não se sabe.','arvore-frutos':'Árvore com cajus: resultados são evidências, não medida de valor pessoal.','habito-contexto':'Contexto, capacidade e motivação influenciam a ação; observar consequências permite ajustar.','processo':'Imaginar processo, identificar obstáculo e planejar resposta se-então.','planta':'Plantar, cuidar, observar e ajustar: ritual simbólico de continuidade.','abas-mentais':'Registrar pendências, separar possibilidades e escolher uma ação.'}.get(v,'Sem imagem necessária'),description='Diagrama editorial diretamente relacionado ao tema; uso somente quando o bloco referencia o asset.' if v else 'Sem imagem para evitar redundância e carga visual.')
(ROOT/'visual-assets.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2))
